import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/component/Navbar";
import SessionWrapper from "@/component/SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} text-white absolute top-0 left-0 z-[-2] h-full w-full bg-[#0a0a0a] bg-[radial-gradient(#1f1f1f_1px,transparent_1px)] bg-[size:24px_24px] before:content-[''] before:absolute before:inset-0 before:bg-[radial-gradient(ellipse_at_top_right,_#8b5cf6_0%,_transparent_60%)] before:opacity-25 before:pointer-events-none`}
      >
        <SessionWrapper>
        <NavBar />

        <div className="absolute top-0 left-0 z-[-2] h-full w-full bg-[#0a0a0a] bg-[radial-gradient(#1f1f1f_1px,transparent_1px)] bg-[size:24px_24px] before:content-[''] before:absolute before:inset-0 before:bg-[radial-gradient(ellipse_at_top_right,_#8b5cf6_0%,_transparent_60%)] before:opacity-25 before:pointer-events-none">
         

          {children}
          
        </div>
        </SessionWrapper>
      </body>
    </html>
  );
}
